services:
  mysql:
    image: mysql:8.0
    environment:
        MYSQL_ROOT_PASSWORD: 123
        MYSQL_DATABASE: banco_queue
        MYSQL_USER: admin
        MYSQL_PASSWORD: 123
    ports:
      - 3307:3307

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
       - 5672:5672
       - 15672:15672